### ISSUE TITLE
Tutorial Install on localhost with xampp

### ISSUE THREAD

**Issue by nhatpham0709** [themesberg/volt-laravel-dashboard#13]
Hello guys I have downloaded your Volt dashboard. It's look stunning on the demo but I could not manage to run it on my own localhost server with Xampp and MySQL. I've followed own your installation guides. However, when I launched it all of the css and js were reported 404 not found and its just plain HTML. Another issue is that when i clicked login, there was error saying that POST method is not allowed. Is it my installation was not done correctly or some issue with your project. Therefore, I would like you guys to have a tutorial of installing it on localhost. Thank you guys a lot. Your work is actually amazing!

**Comment by zoltanszogyenyi** [comment]
@teamupdivision can you help @nhatpham0709 out with his config, please?

Regarding the CSS/JS, make sure that you also run the Gulp command from the docs. This will compile the source JS and Sass files. Read more here: https://volt-pro-laravel-admin-dashboard.updivision.com/documentation/getting-started/build-tools/index.html

@teamupdivision I think we should also add the gulp commands to the installlation part on the docs so that it's clearer for everyone: https://volt-pro-laravel-admin-dashboard.updivision.com/documentation/getting-started/installation/index.html

Thanks!

**Comment by teamupdivision** [comment]
Hi @nhatpham0709,

Thank you for reporting this and for using our products. 

We've updated the documentation to make the steps easier to be followed and to make it clearer how to compile scss files using Laravel mix instead. Please let us know if everything makes sense and if you have any other questions or issues.

Best,
UPDIVISION Team

**Comment by zoltanszogyenyi** [comment]
Thanks @teamupdivision for your help and the update. @nhatpham0709 did you manage to solve your issue?
